# Path to this config can be set via env variable 'CONFIG_FILE'
# App registration must have access to the Azure resources + Admin Consent for AzureAD
# Client Secret can also be set via env variable 'CLIENT_SECRET'
# Redis Access Token can also be set via env variable 'REDIS_TOKEN'

auth:
  type: azure
  tenant_id: notreal-not-real-not-notreal
  client_id: notreal-not-real-not-notreal
  client_secret: notrealnotrealnotreal

redis:
  host: notreal-redisdb.redis.cache.windows.net
  port: 6379
  token: notrealnotrealnotreal

resources:
  - cloud: azure
    type: frontdoor
    subscription_id: notreal-not-real-not-notreal
    resource_group: notreal-rg
    policy_name: notrealpolicy

# This whitelist should be static non-human IPs only
ip_whitelist:
  - 85.0.0.0/24 # my company proxy addresses 1
  - 200.0.0.0/24 # my company proxy addresses 2
